---
name: bloggrid-image
Only:
  classexists: FeaturedImageExtension
---
BlogGridPage:
  extensions:
    - 'FeaturedImageExtension'

---
Only:
  classexists: EmbargoExpirySchedulerExtension
---
BlogGridPage:
  extensions:
    - EmbargoExpirySchedulerExtension

---
Only:
  classexists: FilterableArchiveHolderExtension
---
BlogGridHolder:
  extensions:
    - FilterableArchiveHolderExtension
  pagination_control_tab: Root.Filters
  pagination_insert_before: SubPages
  managed_object_class: BlogGridPage
  managed_object_date_field: Date
BlogGridHolder_Controller:
  extensions:
    - FilterableArchiveHolder_ControllerExtension
BlogGridPage:
  extensions:
    - FilterableArchiveItemExtension
